### ISSUE TITLE
Takedown notice for test failure when Pajek website briefly offline

### ISSUE THREAD

**Issue by skyebend** [statnet/networkDynamic#10]
On 13/09/2021 08:36, Prof Brian Ripley wrote:
> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_networkDynamic.html>.
>
> Please correct before 2021-10-05 to safely retain your package on CRAN.
>
> It seems we need to remind you of the CRAN policy:
>
> 'Packages which use Internet resources should fail gracefully with an informative message
> if the resource is not available or has changed (and not give a check warning nor error).'
>
> This needs correction whether or not the resource recovers.
>
> The CRAN Team
>
For the record, the failure was

--- re-building ‘networkDynamic.Rnw’ using Sweave
Loading required package: network

‘network’ 1.17.1 (2021-06-12), part of the Statnet Project
* ‘news(package="network")’ for changes since last version
* ‘citation("network")’ for citation information
* ‘https://statnet.org’ for help, support, and other information

‘networkDynamic’ 0.11.0 (2021-06-12), part of the Statnet Project
* ‘news(package="networkDynamic")’ for changes since last version
* ‘citation("networkDynamic")’ for citation information
* ‘https://statnet.org’ for help, support, and other information

trying URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip'
Warning in 
download.file("http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip", 
  :
   URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip': 
status was 'Couldn't connect to server'

Error: processing vignette 'networkDynamic.Rnw' failed with diagnostics:
  chunk 47 (label = download_paj)
Error in 
download.file("http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip", 
  :
   cannot open URL 
'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip'

**Comment by CarterButts** [comment]
Yes, I got a similar note about network for this issue.  We should 
probably just supply the files internally and not link to an external 
resource.....

-Carter

**Comment by skyebend** [comment]
On 9/13/21 9:04 PM, CarterButts wrote:
> Yes, I got a similar note about network for this issue. 
If network uses Sampson also, maybe we should add it there? Or was it for a different file?

 We should
> probably just supply the files internally and not link to an external
> resource.....

I imagine that the spurious errors are painful waste of time for CRAN maintainers ... but this is an example in the vignette where we demo how to download external files!  I'll see if it is easier to just rework the example

**Comment by CarterButts** [comment]
Hmm, yes, that is rather an issue.  I note that the initial form letter 
does suggest some possibilities for graceful failure, so that would 
provide another alternative....

-Carter

**Comment by martinamorris** [comment]
We could host the files in the repo, but not include them in the package, so that would be an external web scrape

**Comment by mbojan** [comment]
Alternatively in the long term perhaps let's just add it to https://github.com/statnet/statnet.data and Import it?

**Comment by martinamorris** [comment]
FYI, we have been asked to host the Sampson data several times.  I think we
should do it.
