### ISSUE TITLE
CRAN takedown warning: CRAN packages with 'length > 1 in coercion to logical' reports

### ISSUE THREAD

**Issue by skyebend** [statnet/networkDynamic#12]
That is

Data2LD EHR FastKM ForeCA LearnPCA MLVSBM MRPC PRSim PTXQC RAT RFCCA 
RevGadgets bayestestR bucky causalCmprsk cdcatR cheatR countytimezones 
dmacs drtmle easySdcTable eixport epiR expstudy ffbase gdalUtils 
ggvoronoi hesim idm iheiddown isotracer mstDIF networkDynamic neurobase 
nmaINLA onlineforecast ordinalNet pROC peacesciencer penalizedclr 
psychotools randnet rapportools scDIFtest semTools tableone tiledb 
traineR vortexR

(and some others reported separately).  NEWS for R-devel has

     • Calling && or || with either argument of length greater than one
       now gives a warning (which it is intended will become an error).

and checks with this made into a fatal error can be seen at

https://www.stats.ox.ac.uk/pub/bdr/LENGTH1/

with reproduction instructions in the 00README.txt file.  (As this was 
made a fatal error, only the first error will be shown so please do run 
those instructions before re-submission.)

The problems are occurring in a different package and there is a table 
of which in that 00README.txt,  In some cases this is from misuse but 
you may need to contact the maintainer of the other package -- packages

	kableExtra pracma tidygraph

have already been contacted but ignored us.

Please correct before 2022-04-04 to safely retain your package on CRAN.

**Comment by skyebend** [comment]
I think this might be some logic in the test:
https://www.stats.ox.ac.uk/pub/bdr/LENGTH1/networkDynamic.out

```
> # a network with a point-activated edge
  > cnet7 <- network.initialize(2)
  > cnet7[1,2]<-1
  > activate.edges(cnet7,at=1)
  > check7<-network.dynamic.check(cnet7)
  > c7 <- (check7$vertex.checks==c(T,T) &&
  +        check7$edge.checks==T &&
  +        check7$dyad.checks==T)
   ----------- FAILURE REPORT -------------- 
   --- failure: length > 1 in coercion to logical ---
   --- srcref --- 
  : 
   --- package (from environment) --- 
  testthat
   --- call from context --- 
  NULL
   --- call from argument --- 
  check7$vertex.checks == c(T, T) && check7$edge.checks == T
   --- R stacktrace ---
  
   --- value of length: 2 type: logical ---
  [1] TRUE TRUE
   --- function from context --- 
   --- function search by body ---
   ----------- END OF FAILURE REPORT -------------- 
  Fatal error: length > 1 in coercion to logical
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... [18s/45s] OK
* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 ERROR
See
  ‘/data/gannet/ripley/R/packages/tests-LENGTH1/networkDynamic.Rcheck/00check.log’
for details.
```

**Comment by gvegayon** [comment]
This problem affects `netdiffuseR` as well. I think it suffices with using `all()` around the vector checks, or better, 

```r
with(check7, all(c(vertex.checks, edge.checks, dyad.checks)))
```

**Comment by skyebend** [comment]
Working on this today:

> Dear maintainers,
> 
> This concerns the CRAN packages
> 
>   EpiModel ITNr PAFit ndtv netdiffuseR networkDynamic
>   networkDynamicData statnet tergm tergmLite tsna
> 
> maintained by one of you:
> 
>   George Vega Yon [<g.vegayon@gmail.com>](mailto:g.vegayon@gmail.com): netdiffuseR
>   Martina Morris [<morrism@uw.edu>](mailto:morrism@uw.edu): statnet
>   Matthew Smith [<matt_smith.90@hotmail.co.uk>](mailto:matt_smith.90@hotmail.co.uk): ITNr
>   Pavel N. Krivitsky [<pavel+tergm@unsw.edu.au>](mailto:pavel+tergm@unsw.edu.au): tergm
>   Samuel Jenness [<samuel.m.jenness@emory.edu>](mailto:samuel.m.jenness@emory.edu): EpiModel
>   Samuel M. Jenness [<samuel.m.jenness@emory.edu>](mailto:samuel.m.jenness@emory.edu): tergmLite
>   Skye Bender-deMoll [<skyebend@uw.edu>](mailto:skyebend@uw.edu): networkDynamic ndtv
>         networkDynamicData tsna
>   Thong Pham [<thongphamthe@gmail.com>](mailto:thongphamthe@gmail.com): PAFit
> 
> We have asked for an update fixing the check problems shown at one of
> [<https://www.stats.ox.ac.uk/pub/bdr/LENGTH1_self/networkDynamic.out>](https://www.stats.ox.ac.uk/pub/bdr/LENGTH1_self/networkDynamic.out)
> [<https://www.stats.ox.ac.uk/pub/bdr/LENGTH1/networkDynamic.out>](https://www.stats.ox.ac.uk/pub/bdr/LENGTH1/networkDynamic.out)
> with no update from the maintainer thus far.
> 
> Thus, package 'networkDynamic' is now scheduled for archival on
> 2022-04-18, and archiving this will necessitate also archiving its CRAN
> strong reverse dependencies.
> 
> Please negotiate the necessary actions.

**Comment by skyebend** [comment]
Note: error only reproduced when running Sys.setenv(`_R_CHECK_LENGTH_1_LOGIC2_`="true")`

**Comment by skyebend** [comment]
pushed fixed version to CRAN, awaiting revdep checks etc

**Comment by skyebend** [comment]
v0.1.11 on cran!
