### ISSUE TITLE
Github/master version number/date behind CRAN version

### ISSUE THREAD

**Issue by smjenness** [statnet/networkDynamic#13]
Just a minor note that the nD version number on the master branch, 0.11.0, is behind the published CRAN version, 0.11.2. Same goes with the release dates. Do you want to increment this to be Github > CRAN?

cc: @martinamorris, @chad-klumb

**Comment by mbojan** [comment]
Indeed, I noticed recently that:

```
$ git show origin/master:DESCRIPTION | grep Version
Version: 0.11.0
```

but on `length1_fix` branch

```
$ git show origin/length1_fix:DESCRIPTION | grep Version
Version: 0.11.1
```

so maybe @skyebend sent the 0.11.2 version to CRAN from a branch/commit that he did not push to GH (?)

**Comment by skyebend** [comment]
yup, was waiting for confirmation from CRAN but forgot. pushed now
