### ISSUE TITLE
CRAN requested mandatory updated due to doc failures

### ISSUE THREAD

**Issue by skyebend** [statnet/networkDynamic#21]
> Dear maintainer,

> Please see the problems shown on
[<https://cran.r-project.org/web/checks/check_results_networkDynamic.html>](https://cran.r-project.org/web/checks/check_results_networkDynamic.html).

>Please correct before 2023-12-11 to safely retain your package on CRAN.

>Best,
>-k

```
Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/networkDynamic-00check.html), [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/networkDynamic-00check.html)

Version: 0.11.3
Check: Rd contents
Result: NOTE
  Argument items with no description in Rd file 'print.networkDynamic.Rd':
    ‘\dots’
Flavors: [r-devel-linux-x86_64-debian-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/networkDynamic-00check.html), [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/networkDynamic-00check.html), [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/networkDynamic-00check.html), [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/networkDynamic-00check.html), [r-devel-windows-x86_64](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/networkDynamic-00check.html)

Version: 0.11.3
Check: whether package can be installed
Result: WARN
  Found the following significant warnings:
    wtedgetree.c:628:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
  See ‘/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/networkDynamic.Rcheck/00install.out’ for details.
  * used C compiler: ‘gcc-13 (Debian 13.2.0-5) 13.2.0’
Flavor: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/networkDynamic-00check.html)

Version: 0.11.3
Check: whether package can be installed
Result: WARN
  Found the following significant warnings:
    wtedgetree.c:628:28: warning: format specifies type 'int' but the argument has type 'double' [-Wformat]
  See ‘/data/gannet/ripley/R/packages/tests-clang/networkDynamic.Rcheck/00install.out’ for details.
  * used C compiler: ‘clang version 17.0.5’
Flavor: [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/networkDynamic-00check.html)

Version: 0.11.3
Check: whether package can be installed
Result: WARN
  Found the following significant warnings:
    wtedgetree.c:628:23: warning: format '%d' expects argument of type 'int', but argument 2 has type 'double' [-Wformat=]
  See ‘/data/gannet/ripley/R/packages/tests-devel/networkDynamic.Rcheck/00install.out’ for details.
  * used C compiler: ‘gcc-13 (GCC) 13.2.0’
Flavor: [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/networkDynamic-00check.html)

Version: 0.11.3
Check: whether package can be installed
Result: WARN
  Found the following significant warnings:
    wtedgetree.c:628:23: warning: format '%d' expects argument of type 'int', but argument 2 has type 'double' [-Wformat=]
  See 'd:/Rcompile/CRANpkg/local/4.4/networkDynamic.Rcheck/00install.out' for details.
  * used C compiler: 'gcc.exe (GCC) 12.3.0'
Flavor: [r-devel-windows-x86_64](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/networkDynamic-00check.html)
```

**Comment by skyebend** [comment]
I will also attempt to update my maintainer email to non-csde (tho that may take more than one release?) and attempt to integrate the recent updates

**Comment by skyebend** [comment]
I'm reluctant to install R-devel locally to reproduce the error (unless anybody has an easy solution for switching between R versions locally?)  So I'll try to take a first pass to get the github actions Michael added working to see if I can reproduce there

**Comment by skyebend** [comment]
I'm working through most of the (trivial) doc updates on   https://github.com/statnet/networkDynamic/tree/doc-fix to prep a release

But just noticing that there is a C compiler warning surfaced as they continue to tighten optional flags:
```
wtedgetree.c:628:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
```
I don't really know C,  @CarterButts or @krivit  any quick suggestions to update the diagnostic print function, looks like the line is `  Rprintf("\t.weight=%d\n",edges[e].weight);`?  is it just changing to `%f` instead of `%d` ?

**Comment by krivit** [comment]
> I'm working through most of the (trivial) doc updates on https://github.com/statnet/networkDynamic/tree/doc-fix to prep a release
> 
> But just noticing that there is a C compiler warning surfaced as they continue to tighten optional flags:
> 
> ```
> wtedgetree.c:628:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘double’ [-Wformat=]
> ```
> 
> I don't really know C, @CarterButts or @krivit any quick suggestions to update the diagnostic print function, looks like the line is ` Rprintf("\t.weight=%d\n",edges[e].weight);`? is it just changing to `%f` instead of `%d` ?

Yes, that's exactly right. `ergm` got dinged for the same thing, and it's getting an update shortly. (I don't know how much the two edgetree implementations had diverged, however.)

**Comment by skyebend** [comment]
I think most issues fixed now (@mbojan is it building cleanly for you?), but still need to try to resolve

```
Apparent methods for exported generics not registered:
  as.networkDynamic.siena
See section 'Registering S3 methods' in the 'Writing R Extensions'
manual.
```
flag on win-devel

**Comment by skyebend** [comment]
Submitted to CRAN!  
- Skye, before closing ticket, don't forget to tag release on master once accepted on CRAN
- I didn't get the email change ready in time for this release

**Comment by skyebend** [comment]
>Dear maintainer,
thanks, package networkDynamic_0.11.4.tar.gz is on its way to CRAN.
Best regards,
CRAN teams' auto-check service
Package check result: OK
No changes to worse in reverse depends.
