### ISSUE TITLE
Mandatory CRAN update due to vignette build failure with 3rd party url

### ISSUE THREAD

**Issue by skyebend** [statnet/networkDynamic#24]
Looks like vlado's page with the pajek file format isn't loading.  I think the purpose of code was to demonstrate importing, so if just a temporary problem need to find a fallback
```
 trying URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip'
  Warning in download.file("http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip",  :
    URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip': Timeout of 60 seconds was reached
  
  Error: processing vignette 'networkDynamic.Rnw' failed with diagnostics:
   chunk 47 (label = download_paj) 
  Error in download.file("http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip",  : 
    cannot open URL 'http://vlado.fmf.uni-lj.si/pub/networks/data/esna/Sampson.zip'
  
  --- failed re-building ‘networkDynamic.Rnw’
  
  SUMMARY: processing the following file failed:
    ‘networkDynamic.Rnw’
  
  Error: Vignette re-building failed.
  Execution halted`
```

**Comment by krivit** [comment]
Yeah, I just commended those tests out in `network`.

**Comment by skyebend** [comment]
pavel pinged Vlado on https://github.com/statnet/network/issues/66, i'm also emailing him, but assuming I'll need to comment the sections of the vignette as well

**Comment by skyebend** [comment]
Vlado says there are server outages due to hacking, i'm going to try updating to new github urls
> I intend to move the Pajek network collection to GitHub (https://github.com/bavla/Nets/tree/master/data/Pajek) but it will take some time. If you need some specific networks I can transfer them till the end of this week. 
I put the ESNA data to[ https://github.com/bavla/Nets/tree/master/data/Pajek/esna](https://github.com/bavla/Nets/tree/master/data/Pajek/esna) . You can get the Sampson network at
https://github.com/bavla/Nets/raw/refs/heads/master/data/Pajek/esna/Sampson.zip . I still need to convert the files with network descriptions.

**Comment by skyebend** [comment]
attempted submission with updates https://github.com/statnet/networkDynamic/pull/25

**Comment by skyebend** [comment]
accepted on cran
