### ISSUE TITLE
Warning from CRAN about removal due to check warnings 

### ISSUE THREAD

**Issue by skyebend** [statnet/networkDynamic#8]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_networkDynamic.html>.

Please correct before 2021-06-21 to safely retain your package on CRAN.

Best,
-k

-----
 Version: 0.10.1
Check: S3 generic/method consistency
Result: WARN
    get.edge.attribute:
     function(x, ..., el)
    get.edge.attribute.active:
     function(x, prefix, onset, terminus, length, at, rule,
     active.default, dynamic.only, require.active, return.tea,
     unlist)
    
    get.edge.value:
     function(x, ...)
    get.edge.value.active:
     function(x, prefix, onset, terminus, length, at, rule,
     active.default, dynamic.only, require.active, return.tea,
     unlist)
    
    get.network.attribute:
     function(x, ...)
    get.network.attribute.active:
     function(x, prefix, onset, terminus, length, at, rule, dynamic.only,
     return.tea, unlist)
    
    list.edge.attributes:
     function(x, ...)
    list.edge.attributes.active:
     function(x, onset, terminus, length, at, na.omit, rule, e,
     require.active, active.default, dynamic.only)
    
    list.network.attributes:
     function(x, ...)
    list.network.attributes.active:
     function(x, onset, terminus, length, at, na.omit, rule, dynamic.only)
    
    See section 'Generic functions and methods' in the 'Writing R
    Extensions' manual.
    
    Found the following apparent S3 methods exported but not registered:
     get.edge.attribute.active get.edge.value.active
     get.network.attribute.active list.edge.attributes.active
     list.network.attributes.active
    See section 'Registering S3 methods' in the 'Writing R Extensions'
    manual.
Flavors: r-devel-linux-x86_64-debian-clang, r-devel-linux-x86_64-debian-gcc, r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-devel-windows-x86_64-gcc10-UCRT, r-patched-linux-x86_64, r-patched-solaris-x86

Version: 0.10.1
Check: Rd \usage sections
Result: NOTE
    S3 methods shown with full name in documentation object 'attribute.activity.functions':
     'get.edge.value.active' 'get.network.attribute.active'
     'list.edge.attributes.active' 'list.network.attributes.active'
    
    The \usage entries for S3 methods should use the \method markup and not
    their full name.
    See chapter 'Writing R documentation files' in the 'Writing R
    Extensions' manual.
Flavors: r-devel-linux-x86_64-debian-clang, r-devel-linux-x86_64-debian-gcc, r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-devel-windows-x86_64-gcc10-UCRT, r-patched-linux-x86_64, r-patched-solaris-x86

**Comment by skyebend** [comment]
The release of network 1.17.0 must have changed something about S3 generics?

**Comment by skyebend** [comment]
@CarterButts  did anything come up for networkDynamic in the revdep checks?

**Comment by skyebend** [comment]
Ah, I see pavel flagged the checks: https://github.com/statnet/network/blob/master/revdep/problems.md

**Comment by krivit** [comment]
@skyebend, apologies, I should have pinged you about this personally sooner.

**Comment by skyebend** [comment]
Good news! It looks like there are already commitsfrom @chad-klumb  on master that resolve these issues, (with maybe just some minor tweaks to dependency versions)!  So maybe I 'just' need to try to release a version 0.10.2  to CRAN?  Does this sound familiar to everyone? :grinning:

**Comment by skyebend** [comment]
@krivit what procedure have you been using to run revdep checks?

**Comment by krivit** [comment]
The package `r-lib/revdepcheck` (non-CRAN) and `HenrikBengtsson/revdepcheck.extras` helper functions.

**Comment by krivit** [comment]
I can run the revdepchecks on ND if you'd like. Which branch?

**Comment by CarterButts** [comment]
BTW, @krivit when you ran the checks on network, how long did it take?  I'm doing it now, and it's showing an ETA of 1 day.  I am hoping to push the minor bugfix update tomorrow, assuming that nothing is amiss.  (That shouldn't cause any problems with NetworkDynamic, but if you want to be on the safe side, you might check against the current network master.)

**Comment by krivit** [comment]
@CarterButts , I ran the checks on a cluster, with 16 cores, and I recall it taking under two hours. If you point me to a branch, I can queue a job and maybe have something in a few hours.

**Comment by CarterButts** [comment]
@krivit That would be excellent, if possible!  It was going to take forever on my system.  I've created a release branch for 1.17.1 called v1.17.1, and it so far looks clean, so that's the one to check.  I expect we'll still have the same issues flagged in 1.17.0, but some might get a bit better.  I just want to make sure that nothing got worse....

**Comment by krivit** [comment]
@CarterButts , I would the changes into `v1.17` for the release branch, and then use `v1.17.1` to tag the release once it's on CRAN, but it's your repo. I'll run the tests.

**Comment by krivit** [comment]
@CarterButts revdepcheck done. Took longer than I thought, because I had upgraded R on the cluster and needed to reinstall a whole lot of packages first.

**Comment by CarterButts** [comment]
Cool, thanks!

**Comment by chad-klumb** [comment]
> Good news! It looks like there are already commitsfrom @chad-klumb on master that resolve these issues, (with maybe just some minor tweaks to dependency versions)! So maybe I 'just' need to try to release a version 0.10.2 to CRAN? Does this sound familiar to everyone? 😀

I believe the new generic issues were sorted out last year (network has had some changes since then, but I haven't really been involved with those).

**Comment by skyebend** [comment]
── CHECK ──────────11 packages ──
✓ ergm 3.11.0                            ── E: 1     | W: 0     | N: 2                                                                 
✓ ITNr 0.6.0                             ── E: 0     | W: 0     | N: 0                                                                 
✓ ndtv 0.13.0                            ── E: 0     | W: 0     | N: 0                                                                 
✓ netdiffuseR 1.22.3                     ── E: 0     | W: 0     | N: 1                                                                 
✓ networkDynamicData 0.2.1               ── E: 0     | W: 0     | N: 0                                                                 
✓ PAFit 1.1.0.2                          ── E: 0     | W: 1     | N: 0                                                                 
✓ statnet 2019.6                         ── E: 0     | W: 0     | N: 0                                                                 
✓ tergm 3.7.0                            ── E: 0     | W: 0     | N: 0                                                                 
✓ tsna 0.3.3                             ── E: 0     | W: 0     | N: 0

**Comment by skyebend** [comment]
attempting to release networkDynamic v 0.11.0  to CRAN
